import { z } from "zod";

// Define the User schema using Zod for frontend validation
export const userSchema = z.object({
  id: z.number().optional(), // ID is optional as it's usually generated by the backend
  name: z.string().min(2, "Name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters long")
    .regex(
      /(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[!@#$%^&*])/,
      "Password must contain a letter, a number, and a special character"
    ),
  phone: z.number().min(10, "Phone number must be at least 10 characters"),
  address: z.string().optional(),
  role: z.string().min(1, "Role is required"),
});

// Define the User type based on the Zod schema
export type User = z.infer<typeof userSchema>;
